/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '5/10/17 11:10 AM' with Gradle 2.14-rc-5
 *
 * @author Administrator, @date 5/10/17 11:10 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
